-- For database and table creation

CREATE DATABASE socialmedia;

CREATE TABLE users(
	id SERIAL PRIMARY KEY,
	username VARCHAR(45) NOT NULL UNIQUE,
	email VARCHAR(255) NOT NULL UNIQUE,
	password VARCHAR(255) NOT NULL,
	name VARCHAR(45) NOT NULL UNIQUE,
	cover_pic VARCHAR(255),
	profile_pic VARCHAR(255),
	city VARCHAR(45),
	website VARCHAR(45)
);

CREATE TABLE posts(
	id SERIAL PRIMARY KEY,
	description VARCHAR(300),
	img VARCHAR(255),
	user_id INT NOT NULL REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE,
	createat TIMESTAMP
);

CREATE TABLE comments(
	id SERIAL PRIMARY KEY,
	description VARCHAR(300) NOT NULL,
	createat TIMESTAMP,
	user_id INT NOT NULL REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE,
	post_id INT NOT NULL REFERENCES posts(id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE stories(
	id SERIAL PRIMARY KEY,
	img VARCHAR(255) NOT NULL,
	user_id INT NOT NULL REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE,
	createat TIMESTAMP
);

CREATE TABLE followers (
    id SERIAL PRIMARY KEY,
    follower_id INT NOT NULL REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE,
    following_id INT NOT NULL REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE,
    UNIQUE (follower_id, following_id)
);

CREATE TABLE post_likes (
    id SERIAL PRIMARY KEY,
    user_id INT NOT NULL REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE,
    post_id INT NOT NULL REFERENCES posts(id) ON DELETE CASCADE ON UPDATE CASCADE,
    UNIQUE (user_id, post_id)
);